using System.Collections.Generic;

public class VehicleModelList
{
    public static Dictionary<VehicleGroup, string[]> All()
    {
        return new Dictionary<VehicleGroup, string[]>() {
            {
                VehicleGroup.APC,
                new string[] {
                    "apc"
                }
            },
            {
                VehicleGroup.Arena,
                new string[] {
                    "boxville5",
                    "zr380",
                    "cerberus",
                    "cerberus2",
                    "cerberus3",
                    "deathbike",
                    "slamvan4",
                    "dominator4",
                    "impaler2"
                }
            },
            {
                VehicleGroup.Barrage,
                new string[] {
                    "barrage"
                }
            },
            {
                VehicleGroup.Beach,
                new string[] {
                    "pbus2"
                }
            },
            {
                VehicleGroup.Boats,
                new string[] {
                    "longfin",
                    "toro"
                }
            },
            {
                VehicleGroup.Cemetery,
                new string[] {
                    "tornado6",
                    "btype2",
                    "sanctus",
                    "lurcher",
                    "brigham"
                }
            },
            {
                VehicleGroup.Cheburek,
                new string[] {
                    "cheburek",
                    "ratbike",
                    "slamvan3"
                }
            },
            {
                VehicleGroup.Chernobog,
                new string[] {
                    "chernobog"
                }
            },
            {
                VehicleGroup.Cinema,
                new string[] {
                    "scramjet",
                    "vigilante",
                    "voltic2",
                    "toreador",
                    "jb7002",
                    "deluxo",
                    "stromberg",
                    "rrocket",
                    "shotaro",
                    "dune5"
                }
            },
            {
                VehicleGroup.Cluckin,
                new string[] {
                    "benson2"
                }
            },
            {
                VehicleGroup.Compacts,
                new string[] {
                    "brioso",
                    "brioso2",
                    "brioso3",
                    "weevil",
                    "club",
                    "kanjo",
                    "asbo",
                    "issi3"
                }
            },
            {
                VehicleGroup.Conada2,
                new string[] {
                    "conada2"
                }
            },
            {
                VehicleGroup.Coupes,
                new string[] {
                    "kanjosj",
                    "postlude",
                    "previon",
                    "windsor2",
                    "windsor",
                    "fr36"
                }
            },
            {
                VehicleGroup.Cycles,
                new string[] {
                    "inductor",
                    "inductor2",
                }
            },
            {
                VehicleGroup.Ghetto,
                new string[] {
                    "peyote3",
                    "retinue2",
                    "dynasty",
                    "cheburek",
                    "fagaloa",
                    "tornado5",
                    "youga4",
                    "gburrito2",
                    "eudora",
                    "greenwood",
                    "voodoo",
                }
            },
            {
                VehicleGroup.HalfTrack,
                new string[] {
                    "halftrack"
                }
            },
            {
                VehicleGroup.Helicopters,
                new string[] {
                    "conada",
                    "havok",
                    "volatus",
                    "supervolito",
                    "supervolito2",
                    "swift2",
                }
            },
            {
                VehicleGroup.HumaneLabs,
                new string[] {
                    "brickade2",
                }
            },
            {
                VehicleGroup.Industrial,
                new string[] {
                    "pounder2",
                    "mule4",
                    "phantom3",
                    "hauler2",
                    "phantom2",
                    "mule3",
                    "boxville4",
                }
            },
            {
                VehicleGroup.Karting,
                new string[] {
                    "veto",
                    "veto2",
                }
            },
            {
                VehicleGroup.Khanjari,
                new string[] {
                    "khanjali"
                }
            },
            {
                VehicleGroup.MilitaryBikes,
                new string[] {
                    "squaddie",
                    "manchez2",
                    "winky",
                    "insurgent3",
                }
            },
            {
                VehicleGroup.MilitaryHelicopters,
                new string[] {
                    "annihilator2",
                    "akula",
                    "hunter",
                    "valkyrie",
                    "savage",
                }
            },
            {
                VehicleGroup.MilitaryOpressors,
                new string[] {
                    "oppressor",
                    "oppressor2",
                }
            },
            {
                VehicleGroup.MilitaryPlanes,
                new string[] {
                    "alkonost",
                    "strikeforce",
                    "avenger",
                    "volatol",
                    "nokota",
                    "seabreeze",
                    "pyro",
                    "mogul",
                    "howard",
                    "bombushka",
                    "molotok",
                    "tula",
                    "rogue",
                    "starling",
                    "alphaz1",
                    "hydra",
                }
            },
            {
                VehicleGroup.Motorcycles,
                new string[] {
                    "powersurge",
                    "manchez3",
                    "reever",
                    "shinobi",
                    "manchez2",
                    "stryder",
                    "fcr2",
                    "fcr",
                    "diablous",
                    "diablous2",
                    "esskey",
                    "vortex",
                    "daemon2",
                    "zombiea",
                    "zombieb",
                    "wolfsbane",
                    "nightblade",
                    "manchez",
                    "hakuchou2",
                    "faggio",
                    "faggio3",
                    "defiler",
                    "chimera",
                    "avarus",
                    "cliffhanger",
                    "gargoyle",
                    "bf400",
                    "vindicator",
                    "lectro",
                    "enduro",
                }
            },
            {
                VehicleGroup.Muscle,
                new string[] {
                    "tahoma",
                    "tulip2",
                    "weevil2",
                    "vigero2",
                    "ruiner4",
                    "buffalo4",
                    "dominator7",
                    "dominator8",
                    "gauntlet5",
                    "manana2",
                    "dukes3",
                    "yosemite2",
                    "peyote2",
                    "gauntlet4",
                    "gauntlet3",
                    "vamos",
                    "deviant",
                    "tulip",
                    "clique",
                    "imperator",
                    "impaler",
                    "dominator3",
                    "ellie",
                    "hustler",
                    "hermes",
                    "yosemite",
                    "tampa3",
                    "ruiner2",
                    "sabreGT2",
                    "virgo2",
                    "virgo3",
                    "faction3",
                    "tampa",
                    "nightshade",
                    "moonbeam2",
                    "moonbeam",
                    "faction2",
                    "faction",
                    "chino2",
                    "buccaneer2",
                    "coquette3",
                    "chino",
                    "vigero",
                    "slamVan2",
                    "clique2",
                    "buffalo5",
                    "vigero3",
                    "dominator9",
                    "impaler6",
                }
            },
            {
                VehicleGroup.Offroad,
                new string[] {
                    "boor",
                    "draugur",
                    "patriot3",
                    "verus",
                    "yosemite3",
                    "outlaw",
                    "zhaba",
                    "everon",
                    "vagrant",
                    "hellion",
                    "caracara2",
                    "brutus",
                    "monster3",
                    "bruiser",
                    "freecrawler",
                    "menacer",
                    "caracara",
                    "kamacho",
                    "riata",
                    "nightShark",
                    "technical3",
                    "dune3",
                    "blazer5",
                    "blazer4",
                    "rallyTruck",
                    "trophyTruck",
                    "trophyTruck2",
                    "brawler",
                    "technical",
                    "insurgent",
                    "guardian",
                    "l35",
                    "ratel",
                    "monstrociti",
                    "terminus",
                }
            },
            {
                VehicleGroup.Openwheel,
                new string[] {
                    "openwheel1",
                    "openwheel2",
                    "formula",
                    "formula2",
                    "raptor",
                }
            },
            {
                VehicleGroup.Planes,
                new string[] {
                    "microlight",
                    "nimbus",
                    "luxor2",
                    "velum2",
                }
            },
            {
                VehicleGroup.Police,
                new string[] {
                    "riot2",
                    "polgauntlet",
                    "police5",
                }
            },
            {
                VehicleGroup.Raiju,
                new string[] {
                    "raiju"
                }
            },
            {
                VehicleGroup.Scarab,
                new string[] {
                    "scarab"
                }
            },
            {
                VehicleGroup.Sedans,
                new string[] {
                    "rhinehart",
                    "deity",
                    "cinquemila",
                    "tailgater2",
                    "warrener2",
                    "glendale2",
                    "stafford",
                    "schafter3",
                    "schafter4",
                    "limo2",
                    "schafter5",
                    "schafter6",
                    "cog552",
                    "cog55",
                    "cognoscenti2",
                    "cognoscenti",
                    "primo2",
                    "asterope2",
                    "impaler5",
                }
            },
            {
                VehicleGroup.Slamtruck,
                new string[] {
                    "slamtruck",
                }
            },
            {
                VehicleGroup.SportClassic,
                new string[] {
                    "everon2",
                    "panthere",
                    "r300",
                    "sentinel4",
                    "tenf2",
                    "tenf",
                    "sm722",
                    "omnisegt",
                    "corsita",
                    "comet7",
                    "cypher",
                    "sultan3",
                    "growler",
                    "vectre",
                    "comet6",
                    "remus",
                    "jester4",
                    "rt3000",
                    "zr350",
                    "euros",
                    "futo2",
                    "italirsx",
                    "penumbra2",
                    "coquette4",
                    "sugoi",
                    "vstr",
                    "sultan2",
                    "imorgon",
                    "komoda",
                    "jugular",
                    "zion3",
                    "locust",
                    "nebula",
                    "neo",
                    "issi7",
                    "drafter",
                    "paragon",
                    "paragon2",
                    "schlagen",
                    "italigto",
                    "swinger",
                    "jester3",
                    "michelli",
                    "flashgt",
                    "gb200",
                    "hotring",
                    "comet5",
                    "z190",
                    "neon",
                    "revolter",
                    "gt500",
                    "viseris",
                    "savestra",
                    "streiter",
                    "sentinel3",
                    "raiden",
                    "pariah",
                    "comet4",
                    "rapidgt3",
                    "retinue",
                    "ardent",
                    "torero",
                    "cheetah2",
                    "turismo2",
                    "infernus2",
                    "ruston",
                    "specter2",
                    "specter",
                    "comet3",
                    "elegy",
                    "tampa2",
                    "lynx",
                    "tropos",
                    "omnis",
                    "seven70",
                    "bestiagts",
                    "mamba",
                    "verlierer2",
                    "schafter3",
                    "schafter4",
                    "feltzer3",
                    "casco",
                    "kuruma",
                    "kuruma2",
                    "stingertt",
                    "gauntlet6",
                    "coureur",
                }
            },
            {
                VehicleGroup.Streamer216,
                new string[] {
                    "streamer216"
                }
            },
            {
                VehicleGroup.Submarines,
                new string[] {
                    "avisa",
                }
            },
            {
                VehicleGroup.Supers,
                new string[] {
                    "virtue",
                    "entity3",
                    "lm87",
                    "torero2",
                    "zeno",
                    "ignus",
                    "champion",
                    "tigon",
                    "furia",
                    "zorrusso",
                    "krieger",
                    "emerus",
                    "s80",
                    "thrax",
                    "deveste",
                    "tyrant",
                    "tezeract",
                    "taipan",
                    "entity2",
                    "autarch",
                    "sc1",
                    "cyclone",
                    "visione",
                    "xa21",
                    "vagner",
                    "gp1",
                    "italigtb",
                    "italigtb2",
                    "nero",
                    "nero2",
                    "tempesta",
                    "penetrator",
                    "tyrus",
                    "le7b",
                    "sheava",
                    "pfister811",
                    "prototipo",
                    "reaper",
                    "fmj",
                    "sultanrs",
                    "banshee2",
                    "t20",
                    "osiris",
                    "turismo3",
                }
            },
            {
                VehicleGroup.SUVs,
                new string[] {
                    "issi8",
                    "granger2",
                    "iwagen",
                    "baller7",
                    "astron",
                    "jubilee",
                    "seminole2",
                    "landstalker2",
                    "rebla",
                    "novak",
                    "toros",
                    "stretch",
                    "contender",
                    "xls2",
                    "baller3",
                    "baller4",
                    "baller5",
                    "baller6",
                    "vivanite",
                    "aleutian",
                    "cavalcade3",
                    "baller8",
                    "dorado",
                }
            },
            {
                VehicleGroup.Terrorbyte,
                new string[] {
                    "terbyte"
                }
            },
            {
                VehicleGroup.Thruster,
                new string[] {
                    "thruster"
                }
            },
            {
                VehicleGroup.Towtruck,
                new string[] {
                    "towtruck4",
                }
            },
            {
                VehicleGroup.TrailerLarge,
                new string[] {
                    "trailerlarge"
                }
            },
            {
                VehicleGroup.TrailerSmall,
                new string[] {
                    "trailersmall2"
                }
            },
            {
                VehicleGroup.Tuners,
                new string[] {
                    "kanjosj",
                    "postlude",
                    "previon",
                    "cypher",
                    "sultan3",
                    "growler",
                    "vectre",
                    "dominator7",
                    "comet6",
                    "remus",
                    "jester4",
                    "tailgater2",
                    "warrener2",
                    "rt3000",
                    "zr350",
                    "dominator8",
                    "euros",
                    "futo2",
                    "calico"
                }
            },
            {
                VehicleGroup.Valentine,
                new string[] {
                    "btype3"
                }
            },
            {
                VehicleGroup.Vans,
                new string[] {
                    "journey2",
                    "surfer3",
                    "youga3",
                    "speedo4",
                    "youga2",
                    "rumpo3",
                    "minivan2",
                    "boxville6"
                }
            },
            {
                VehicleGroup.Vetir,
                new string[] {
                    "vetir"
                }
            },
            {
                VehicleGroup.Wastelander,
                new string[] {
                    "wastelander"
                }
            },
            {
                VehicleGroup.WeaponizedBoats,
                new string[] {
                    "dinghy5",
                    "patrolboat",
                    "tug"
                }
            }
        };
    }
}
